INHERIT: ./mkdocs.maybe-insiders.yml

site_name: FineSQL
site_description: FineSQL, async and await, focused on developer experience.
site_url: https://finesql.mohir.cloud/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue-grey
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue-grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

  features:
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
  custom_dir: overrides

repo_name: goldendevuz/finesql
repo_url: https://github.com/goldendevuz/finesql

plugins:
  search:
  social:
  macros:
    include_yaml:
      - members: data/members.yml

nav:
  - Get started: index.md
  - API: api.md
  - Examples: examples.md
  - Resources:
      - resources/index.md
      - help.md
      - contributing.md
      - management-tasks.md
  - About:
      - about/index.md
      - management.md
  - release-notes.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - codehilite
  - footnotes
  - abbr
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.highlight:
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # pymdownx blocks
  - pymdownx.blocks.admonition:
      types:
        - note
        - attention
        - caution
        - danger
        - error
        - tip
        - hint
        - warning
        - info
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true

  # Other extensions
  - mdx_include

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/goldendevuz/finesql
    - icon: fontawesome/brands/telegram
      link: https://telegram.com/goldendevuz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/goldendevuz
    - icon: fontawesome/brands/dev
      link: https://dev.to/goldendevuz
    - icon: fontawesome/brands/medium
      link: https://medium.com/@goldendevuz
    - icon: fontawesome/solid/globe
      link: https://gold.mohir.cloud
  version:
    provider: mike
    default: latest
    alias: true

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

hooks:
  - scripts/mkdocs_hooks.py
